version: '2'

services:
  backend:
    build: ./docker/node
    mem_limit: 256M
    volumes:
    - ./src/server:/home/node/app
    ports:
    - '9229:9229'
    - '3000:3000'
    networks:
    - dev-network
  webpack-dev-server:
    build: ./docker/node
    mem_limit: 512M
    volumes:
    - ./src/client:/home/node/app
    ports:
    - '8080:8080'
    - '8888:8888'
    networks:
    - dev-network
networks:
  dev-network:
    driver: bridge
