version: '2'

services:
  app:
    build: ./docker/node
    command: npm run start
    volumes:
    - ./:/home/node/app
    - ./logs/npm:/home/node/.npm/_logs
    networks:
    - local
    ports:
    - '9229:9229'
    - '3000:3000'
networks:
  local:
    driver: bridge
    ipam:
      driver: default
