version: '3'

services:
  backend:
    build: ./src/server
    networks:
    - production-network
  webpack:
    build: ./src/client
    volumes:
    - assets:/home/node/app/dist
  nginx:
    build: ./docker/nginx
    volumes:
    - assets:/var/www
    ports:
    - '80:80'
    - '443:443'
    networks:
    - production-network
networks:
  production-network:
    driver: bridge
volumes:
  assets:
