version: '2'

services:
  backend:
    build: ./docker/node
    command: npm run start:${MODE}
    volumes:
    - ./:/home/node/app
    - ./logs/npm:/home/node/.npm/_logs
    networks:
    - local
    ports:
    - '3000:3000'
    - '9229:9229'
  frontend:
    build: ./docker/node
    command: npm run webpack:${MODE}
    volumes:
    - ./:/home/node/app
    - ./logs/npm:/home/node/.npm/_logs
    links:
      - nginx
    networks:
    - local
    ports:
    - '8080:8080'
  nginx:
    build: ./docker/nginx
    volumes:
    - ./dist:/var/www
    - ./logs/nginx:/var/log/nginx
    links:
      - backend
    ports:
    - '80:80'
    networks:
    - local
networks:
  local:
    driver: bridge
    ipam:
      driver: default
