version: '3'

services:
  backend:
    build: ./src/server
    command: npm run start
    environment:
    - NODE_ENV=production
    networks:
    - project-network
  webpack:
    build: src/client
    command: npm run build
    environment:
    - NODE_ENV=production
    volumes:
    - assets:/home/node/app/dist
  nginx:
    build: ./docker/nginx
    volumes:
    - assets:/var/www
    links:
      - backend
    ports:
    - '80:80'
    - '443:443'
    networks:
    - project-network
networks:
  project-network:
    driver: bridge
    ipam:
      driver: default
volumes:
  assets:
